# Generated by Django 4.1.2 on 2022-11-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
