# Generated by Django 4.1.2 on 2022-11-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='dayandtime',
            field=models.TimeField(),
        ),
    ]
